site_name: H.G.I.2
site_url: https:// 
repo_url: https://www.github.com/tobias-gh-schulz/H.G.I.2
repo_name: tobias-gh-schulz/H.G.I.2

theme:
  name:
    material
  language:
    en
  plugins:
    - search
nav:
  - Introduction: 'index.md'
  - Examples: 'examples.md'
  - Models: 'models.md'